######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 27 18:13:45 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += courseRecord.h doublySortedLinkedList.h hashTable.h objects.h
SOURCES += main.cpp
